/**
 * SOP模板数据 - 所有模块和SOP子项定义
 * table_ref: 对应的数据库表.字段
 */

let sortOrder = 0;

const modules = [
    {
        sort_order: 1,
        name: '基础信息',
        items: [
            { name: '产品分类', table_ref: 'products.category', sort_order: ++sortOrder, is_data_column: true },
            { name: 'ASIN', table_ref: 'products.asin', sort_order: ++sortOrder, is_data_column: true },
            { name: '产品名称', table_ref: 'products.name', sort_order: ++sortOrder, is_data_column: true },
            { name: '运营情况', table_ref: 'products.status', sort_order: ++sortOrder, is_data_column: true },
            { name: '已完成百分比', table_ref: 'products.overall_progress', sort_order: ++sortOrder, is_data_column: true },
            { name: '评价管理概览', instruction_text: '快速查看评价数据', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 2,
        name: '评价管理',
        items: [
            { name: '更新时间', table_ref: 'product_sop_records.updated_at', sort_order: ++sortOrder, is_data_column: true },
            { name: '星级', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '评分数', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: 'VINE评分', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '直评', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '首页差评', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: 'VINE年龄设置', instruction_text: '产品做VINE之前先不要在标题和五点上把产品的适用年龄定得太泛（而是定准确且保守的适用年龄），婴儿产品不用。', sort_order: ++sortOrder, is_data_column: false },
            { name: '注册VINE', instruction_text: '产品上架第一时间做VINE', sort_order: ++sortOrder, is_data_column: false },
            { name: '收集无评星产品做直评', instruction_text: '收集所有无评星或评星小于4的产品来做直评', sort_order: ++sortOrder, is_data_column: false },
            { name: '扩展VINE人群范围', instruction_text: 'VINE之后将人群范围扩展，比如年龄范围写大一点', sort_order: ++sortOrder, is_data_column: false },
            { name: '拆分差评变体', instruction_text: '把差评多且影响listing评分的变体拆出来避免因评分差影响其它变体影响转化', sort_order: ++sortOrder, is_data_column: false },
            { name: 'AI分析产品评价', instruction_text: '用AI工具分析更多产品评价，找产品痛点、焦虑点', sort_order: ++sortOrder, is_data_column: false },
            { name: '分析客户爽点', instruction_text: '分析客户爽点', sort_order: ++sortOrder, is_data_column: false },
            { name: '痛爽点转卖点', instruction_text: '把痛点和爽点转换为产品的卖点（把痛点和爽点投喂给GPT后让GPT帮改标题五点，改图片A+）', sort_order: ++sortOrder, is_data_column: false },
            { name: '放大客户焦虑打法', instruction_text: '问GPT:这个产品___,五点和图片是___,怎样让客人的焦虑点转换为产品卖点，给出可执行的行动步骤：P(焦虑) → R(安抚) → P(证据) → A(行动)', sort_order: ++sortOrder, is_data_column: false },
            { name: '焦虑打法补充', instruction_text: '屏幕时间、发育落后、安全材质、呛咽、清洁卫生、耐用度等焦虑点，每条都要在标题/主图/五点/A+、视频、QA、客服话术里找到安抚点', sort_order: ++sortOrder, is_data_column: false },
            { name: '做售后卡片/明信片', instruction_text: '为此产品做售后卡片，明信片，以避免后继的中差评问题', sort_order: ++sortOrder, is_data_column: false },
            { name: 'VINE刷评', instruction_text: '使服务商做VINE或用刷单不留评安全刷单法', sort_order: ++sortOrder, is_data_column: false },
            { name: '埋入竞品出单精准长尾词', instruction_text: '把主要出单词或从广告洞察找到3个搜索量中等的竞品出单精准长尾词，埋入listing里（五点描述和ST里）添加其权重', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 3,
        name: '竞品分析',
        items: [
            { name: '更新时间', table_ref: 'product_sop_records.updated_at', sort_order: ++sortOrder, is_data_column: true },
            { name: '竞品数量', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '收藏竞品到欧鹭', instruction_text: '把收集到的竞品收藏到欧鹭里，并每周每月去看竞品的变化情况', sort_order: ++sortOrder, is_data_column: false },
            { name: '新品首页竞品分析', instruction_text: '对新品/首页新品进行竞品分析', sort_order: ++sortOrder, is_data_column: false },
            { name: '反查优秀产品关键词', instruction_text: '反查前三项购买率大于1000转化率大于15%的产品的所有优秀有流量的关键词并进入我们的LISTING里面', sort_order: ++sortOrder, is_data_column: false },
            { name: '反查自己的LISTING', instruction_text: '反查自己的LISTING的关键词，以查漏补缺，把自己的ASIN当作竞品来反差', sort_order: ++sortOrder, is_data_column: false },
            { name: '亲自把玩产品', instruction_text: '把产品亲自把玩一遍以熟悉产品功能卖点', sort_order: ++sortOrder, is_data_column: false },
            { name: '竞品差距分析', instruction_text: '挑几个ASIN找出我司ASIN和竞品的差距并提出修改意见', sort_order: ++sortOrder, is_data_column: false },
            { name: 'GPT挖掘意外卖点', instruction_text: '把意想不到的产品卖点、受众、用途、场景、关键词或其它细节等用GPT来问', sort_order: ++sortOrder, is_data_column: false },
            { name: 'GPT分析listing改进空间', instruction_text: '将产品前台显示的标题五点图片A+逐个投给GPT做分析：还有什么改进空间。关键词也全部投给他让它补充更多关键词', sort_order: ++sortOrder, is_data_column: false },
            { name: '选品扩展', instruction_text: '通过1688，淘宝，亚马逊检查此产品近期新上架的新品/升级换代品', sort_order: ++sortOrder, is_data_column: false },
            { name: '做产品视频和图片', instruction_text: '去fivework找人做产品视频和新的一套图片', sort_order: ++sortOrder, is_data_column: false },
            { name: '竞品工具分析', instruction_text: '竞品分析：用工具（sif/js/卖家精灵/H10）或竞品分析表做分析', sort_order: ++sortOrder, is_data_column: false },
            { name: '检查关键词排名', instruction_text: '检查前10名的关键词排名并具体列出每个关键词的排名位置（自然位及广告位）', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 4,
        name: '文案和关键词优化',
        items: [
            { name: '更新时间', table_ref: 'product_sop_records.updated_at', sort_order: ++sortOrder, is_data_column: true },
            { name: '广告出单词', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '主打词', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '标题', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '五点描述', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '收集品牌分析关键词', instruction_text: '针对每个产品，在品牌分析页面的关键词收集和整理并用于开广告', sort_order: ++sortOrder, is_data_column: false },
            { name: '按RUFUS和COSMO算法优化', instruction_text: '按RUFUS和COSMO的算法解释来优化listing', sort_order: ++sortOrder, is_data_column: false },
            { name: '扩展100+关键词', instruction_text: '扩展100个以上的相关关键词用于开广告', sort_order: ++sortOrder, is_data_column: false },
            { name: '广告出单词加入ST', instruction_text: '把广告出单词加入st，或有一定搜索量的加入listing', sort_order: ++sortOrder, is_data_column: false },
            { name: '更换主打关键词', instruction_text: '根据数据更换主打关键词', sort_order: ++sortOrder, is_data_column: false },
            { name: '标题加入大品牌描述词', instruction_text: '竞品少的新品，在标题中加入大品牌的描述词', sort_order: ++sortOrder, is_data_column: false },
            { name: '突出安全性', instruction_text: '突出婴儿/非婴儿产品安全性：加上安全性关键词，加强品牌特性。1材质安全性，2无窒息风险，3有ASTM/CPSIA证书，4设计安全', sort_order: ++sortOrder, is_data_column: false },
            { name: 'plastic换成BPA Free', instruction_text: '婴儿塑胶产品：把方案里的plastic换成BPA Free Plastic或Non-Toxic Plastic', sort_order: ++sortOrder, is_data_column: false },
            { name: '移动端专属优化', instruction_text: '确保标题前30字符含核心词，五点的前两点能完整显示并能够把产品的主要卖点说清楚；图片文字在手机端清晰可读', sort_order: ++sortOrder, is_data_column: false },
            { name: '扩展五点描述', instruction_text: '加多第六第七第八点', sort_order: ++sortOrder, is_data_column: false },
            { name: '五点增加使用场景', instruction_text: '五点描述中增加关于产品的更多具体使用场景（适合什么对象，什么场合，什么节日的礼物都要在五点里写清楚出来）', sort_order: ++sortOrder, is_data_column: false },
            { name: '节日词/情感词/礼品词', instruction_text: '将节日词、情感词、礼品词等在Listing中可做适当呈现', sort_order: ++sortOrder, is_data_column: false },
            { name: '试开广告检查推荐词', instruction_text: '用试开广告的方法检查推荐词是否有不相关的词，如有则优化listing', sort_order: ++sortOrder, is_data_column: false },
            { name: '标题五点AB测试', instruction_text: '标题五点做AB测试', sort_order: ++sortOrder, is_data_column: false },
            { name: '本地化Listing优化', instruction_text: '针对不同人群（如美国的西班牙语人群）站点（如DE/FR）翻译文案并植入本地搜索习惯词', sort_order: ++sortOrder, is_data_column: false },
            { name: 'listing深度再优化', instruction_text: '将listing的图片标题五点全部逐个发给GPT问改进空间', sort_order: ++sortOrder, is_data_column: false },
            { name: '婴儿产品QA模板', instruction_text: 'QA不能跳过：婴儿产品在A+新建QA模块加入QA问答：Q1适用年龄疑问, Q2 BPA认证, Q3清洁方法。每条QA给出标准回复模板', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 5,
        name: '广告管理',
        items: [
            { name: '更新日期', table_ref: 'product_sop_records.updated_at', sort_order: ++sortOrder, is_data_column: true },
            { name: '自动广告数据', table_ref: 'product_sop_records.remark', instruction_text: '曝光和前一个月变化对比', sort_order: ++sortOrder, is_data_column: true },
            { name: '手动关键词广告', table_ref: 'product_sop_records.remark', instruction_text: '曝光和前一个月变化对比', sort_order: ++sortOrder, is_data_column: true },
            { name: '海王广告数据', table_ref: 'product_sop_records.remark', instruction_text: '曝光/点击/花费/转化（曝光和前一个月变化对比）', sort_order: ++sortOrder, is_data_column: true },
            { name: '视频广告数据', table_ref: 'product_sop_records.remark', instruction_text: '曝光/ACOS（曝光和前一个月变化对比）', sort_order: ++sortOrder, is_data_column: true },
            { name: '标签打法数据', table_ref: 'product_sop_records.remark', instruction_text: '曝光和前一个月变化对比', sort_order: ++sortOrder, is_data_column: true },
            { name: 'TOS广告数据', table_ref: 'product_sop_records.remark', instruction_text: '曝光和前一个月变化对比', sort_order: ++sortOrder, is_data_column: true },
            { name: 'ASIN广告数据', table_ref: 'product_sop_records.remark', instruction_text: '曝光和前一个月变化对比', sort_order: ++sortOrder, is_data_column: true },
            { name: '闭环互投数据', table_ref: 'product_sop_records.remark', instruction_text: '曝光和前一个月变化对比', sort_order: ++sortOrder, is_data_column: true },
            { name: 'SD广告数据', table_ref: 'product_sop_records.remark', instruction_text: '曝光和前一个月变化对比', sort_order: ++sortOrder, is_data_column: true },
            { name: 'SBC广告数据', table_ref: 'product_sop_records.remark', instruction_text: '曝光和前一个月变化对比', sort_order: ++sortOrder, is_data_column: true },
            { name: '列出广告关键词', table_ref: 'product_sop_records.remark', instruction_text: '列出此产品所有主要的广告关键词', sort_order: ++sortOrder, is_data_column: true },
            { name: '查询广告位稳定情况', table_ref: 'product_sop_records.remark', instruction_text: '用sif等工具查询这些主要广告关键词的广告位稳定情况', sort_order: ++sortOrder, is_data_column: true },
            { name: '开齐所有广告类型', instruction_text: '开齐所有广告类型：ASIN广告、核心词广告、海王、标签、TOS、ROS、类目/跨类目、SP闭环、SD闭环、SBV、SBC、SD定向', sort_order: ++sortOrder, is_data_column: false },
            { name: '按卖点开广告', instruction_text: '所有广告类型能按卖点开的都按卖点来开广告，且把所有重要卖点和属性都要开广告', sort_order: ++sortOrder, is_data_column: false },
            { name: '多开自动广告', instruction_text: '多开自动广告（10组）并去停掉表现差的自动广告（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '按卖点分组关键词', instruction_text: '通过工具收集关键词并按照属性卖点分类关键词建组，覆盖：使用场景、目标人群、痛点与收益、季节/节日、合规与信任、差异化、组合与增值、情绪/礼品、价格与促销', sort_order: ++sortOrder, is_data_column: false },
            { name: '手动精准广告', instruction_text: '把表现好的搜索词做成手动精准：从自动广告、广泛广告的报告里挑出表现好的搜索词做成手动精准，出价要比原来高', sort_order: ++sortOrder, is_data_column: false },
            { name: '手动关键词广告优化', instruction_text: '手动关键词广告（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '广告海王打法', instruction_text: '广告海王打法（主力产品先做）（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '标签打法广告', instruction_text: '标签打法广告（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '视频广告', instruction_text: '做视频广告：做出一个别致新颖的推广视频来开广告（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '视频广告VCPM', instruction_text: '开视频广告时除了开点击的方式，都要同时开VCPM的形式（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '节日加大闭环出价', instruction_text: '节日活动前，加大产品流量闭环广告出价', sort_order: ++sortOrder, is_data_column: false },
            { name: '关键词上首页TOS', instruction_text: '关键词上首页【TOS广告、冲量关键词法】（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '50+词TOS广告', instruction_text: '每个出单品做50个以上相关词的TOS广告', sort_order: ++sortOrder, is_data_column: false },
            { name: 'ASIN广告加竞品', instruction_text: '将首页的竞品加入到ASIN广告（或检查已有的对应广告的表现效果并做优化）', sort_order: ++sortOrder, is_data_column: false },
            { name: '多做ASIN广告', instruction_text: '多做ASIN广告：找同款或相似相搭配的产品来做产品广告（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '类目跨类目广告', instruction_text: '开类目、跨类目广告（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '细化类目广告', instruction_text: '用新的方式--细化开类目、跨类目广告（或优化已开广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '受众TV广告', instruction_text: '对比较有特色或很吸引人的产品做SD受众广告和TV广告（耗费比较高，慎做）', sort_order: ++sortOrder, is_data_column: false },
            { name: '新品改为提升与降低', instruction_text: '新品凡是有经常出单，或有大量出单希望的，或广告效果好的，出价策略改为提升与降低', sort_order: ++sortOrder, is_data_column: false },
            { name: '按销售速度调预算', instruction_text: '按销售速度调广告分组的预算（和转移广告活动一起体系）', sort_order: ++sortOrder, is_data_column: false },
            { name: '不断否定不相关词', instruction_text: '不断否定广告跑出来的不相关词或ASIN商品（每次至少否定5-20个词或ASIN）', sort_order: ++sortOrder, is_data_column: false },
            { name: '关键词否定新方法', instruction_text: '实操关键词否定新方法：用关键词扩展工具来收集不相关词来否定', sort_order: ++sortOrder, is_data_column: false },
            { name: '精美SBV视频', instruction_text: '做一个很吸引人的SBV视频广告来吸引人进入产品页面或进行旗舰店页面', sort_order: ++sortOrder, is_data_column: false },
            { name: '提前联想广告方式', instruction_text: '像去年广告加入了情感词广告，夏季产品也要提前通过GPT多联想广告方式和广告词，以在黑五期间获取更高曝光', sort_order: ++sortOrder, is_data_column: false },
            { name: '小词精准广告', instruction_text: '扩展一些小词开精准广告并拿AC（或检查已有的对应广告的表现效果并做优化）', sort_order: ++sortOrder, is_data_column: false },
            { name: '万物皆可检检漏广告', instruction_text: '用"万物皆可检"打法做各个产品的检漏广告（低价高广告位的方法开够500个以上的广告词）', sort_order: ++sortOrder, is_data_column: false },
            { name: '低价自动广告', instruction_text: '开低价自动广告（四种匹配全开）（自动海王广告）', sort_order: ++sortOrder, is_data_column: false },
            { name: '广告曝光打法', instruction_text: '做"广告曝光打法"提升低曝光量广告的曝光量', sort_order: ++sortOrder, is_data_column: false },
            { name: '扩展礼品情感关键词', instruction_text: '扩展礼品类，情感类的关键词', sort_order: ++sortOrder, is_data_column: false },
            { name: '按卖点分组重投广告', instruction_text: '按卖点分组广告词重新投放广告', sort_order: ++sortOrder, is_data_column: false },
            { name: '大曝光SP加视频', instruction_text: '将曝光量大的SP广告都加上视频提高点击', sort_order: ++sortOrder, is_data_column: false },
            { name: '好表现活动移无限额', instruction_text: '把表现好的广告活动从分组里脱离出去移动到无限额的分组', sort_order: ++sortOrder, is_data_column: false },
            { name: '分析销量上涨ASIN补库存', instruction_text: '近期销量上涨的ASIN及时分析是否需要增补库存', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 6,
        name: '站外推广',
        items: [
            { name: '日期', table_ref: 'product_sop_records.updated_at', sort_order: ++sortOrder, is_data_column: true },
            { name: '站外站点', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: 'RebateKey', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: 'SNAGSHOUT', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: 'Rebaid', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '上传rebatekey', instruction_text: '上传产品到rebatekey平台', sort_order: ++sortOrder, is_data_column: false },
            { name: '上传Snagshout', instruction_text: '上传产品到snagshout平台', sort_order: ++sortOrder, is_data_column: false },
            { name: '上传Rebaid', instruction_text: '上传产品到rebaid平台', sort_order: ++sortOrder, is_data_column: false },
            { name: '服务商站外推广', instruction_text: '通过服务商进行站外推广', sort_order: ++sortOrder, is_data_column: false },
            { name: '秒杀后站外维持', instruction_text: '秒杀后的第二天安排一场站外以维持排名和销量', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 7,
        name: '关联流量',
        items: [
            { name: '更新日期', table_ref: 'product_sop_records.updated_at', sort_order: ++sortOrder, is_data_column: true },
            { name: '已A+关联', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: 'POST计划表', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: 'A+关联引流', instruction_text: '做好A+关联，通过关联页面引流', sort_order: ++sortOrder, is_data_column: false },
            { name: '做POST', instruction_text: '发帖做POST增加曝光', sort_order: ++sortOrder, is_data_column: false },
            { name: '合并变体', instruction_text: '合并变体集中流量', sort_order: ++sortOrder, is_data_column: false },
            { name: '旗舰店横幅宣告', instruction_text: '新品上架后让美工做旗舰店首页的横幅在旗舰店宣告', sort_order: ++sortOrder, is_data_column: false },
            { name: '独立站Google Ads', instruction_text: '独立站投放广告：Google Ads广告，投放品牌词或产品关键词等，导流至亚马逊Listing', sort_order: ++sortOrder, is_data_column: false },
            { name: '独立站+社交多平台发布', instruction_text: '产品上架前，第一时间在独立站上传和发布，并让美工发布图文或视频到YouTube, X, FB, IG, Pinterest, TK等平台', sort_order: ++sortOrder, is_data_column: false },
            { name: '加入内容创作者计划', instruction_text: '把产品加入亚马逊内容创作者计划', sort_order: ++sortOrder, is_data_column: false },
            { name: '做虚拟捆绑', instruction_text: '做虚拟捆绑增加关联', sort_order: ++sortOrder, is_data_column: false },
            { name: '像素级属性对标', instruction_text: '蹭大卖流量：极致的"像素级"属性对标，确保类目节点完全一致，核心属性高度重合，放到同一个对比栏里吸走流量', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 8,
        name: '促销流量',
        items: [
            { name: '更新日期', table_ref: 'product_sop_records.updated_at', sort_order: ++sortOrder, is_data_column: true },
            { name: '秒杀推荐', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '有无参考价', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '竞品价格分析', instruction_text: '竞品价格分析，把竞品的最高价、最低价、平均做统计并总结我们的价格是否有竞争力和是否需要调价', sort_order: ++sortOrder, is_data_column: false },
            { name: '检查PRIME折扣和优惠券', instruction_text: '检查产品是否能做PRIME折扣和优惠券', sort_order: ++sortOrder, is_data_column: false },
            { name: '品牌定制促销', instruction_text: '做品牌定制促销', sort_order: ++sortOrder, is_data_column: false },
            { name: '购物车优惠券', instruction_text: '为产品设置购物车优惠券，使加购而不购买者回购', sort_order: ++sortOrder, is_data_column: false },
            { name: '设置目标价', instruction_text: '设置目标价（使其达20%利润）：算广告费/不算广告费', sort_order: ++sortOrder, is_data_column: false },
            { name: '设置优惠券', instruction_text: '设置优惠券，30美元以上开启降具体金额而不是百分比', sort_order: ++sortOrder, is_data_column: false },
            { name: '积极申报BD,LD做WOOT', instruction_text: '积极申报BD,LD，做WOOT秒杀', sort_order: ++sortOrder, is_data_column: false },
            { name: '买一送一带动销量', instruction_text: '对多选项产品通过买一送一活动把其它选项的销量带起来，类似做引流款', sort_order: ++sortOrder, is_data_column: false },
            { name: '企业价格和批发价格', instruction_text: '填写企业价格和设置好批发价格（数量折扣）', sort_order: ++sortOrder, is_data_column: false },
            { name: '螺旋打法提升出单', instruction_text: '用"螺旋打法"提升产品出单量—螺旋打法一个季度内至少做4次', sort_order: ++sortOrder, is_data_column: false },
            { name: '利润分析', instruction_text: '结合实际的推广费用及其它杂费，做一次具体的利润分析', sort_order: ++sortOrder, is_data_column: false },
            { name: '设置引流款和利润款', instruction_text: '设置引流款和利润款', sort_order: ++sortOrder, is_data_column: false },
            { name: '9.99美元引流打法', instruction_text: '9.99美元引流打法', sort_order: ++sortOrder, is_data_column: false },
            { name: '参考价/GIFT选项/最大订单数量', instruction_text: '参考价，GIFT选项、最大订单数量填写', sort_order: ++sortOrder, is_data_column: false },
            { name: '多站点同步', instruction_text: '把夏季产品用上传表格的方式手动同步到墨西哥和加拿大站并在墨加站设置好折扣（欧洲同步到小站点）', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 9,
        name: '产品属性优化',
        items: [
            { name: '优化产品属性', instruction_text: '通过填写完整的产品属性（如适用年龄、材质、安全认证等），提高列表的相关性，让RUFUS更容易收录', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 10,
        name: '视觉优化',
        items: [
            { name: '更新日期', table_ref: 'product_sop_records.updated_at', sort_order: ++sortOrder, is_data_column: true },
            { name: '转化率/浏览量/点击量', table_ref: 'product_sop_records.remark', instruction_text: '查看产品的转化率，浏览量，点击量等数据', sort_order: ++sortOrder, is_data_column: true },
            { name: '视频数量及顺序', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '视频标题', table_ref: 'product_sop_records.remark', sort_order: ++sortOrder, is_data_column: true },
            { name: '分析转化差原因', instruction_text: '分析转化差，点击量低的原因，并提出改进措施', sort_order: ++sortOrder, is_data_column: false },
            { name: '主图不符合美国审美优化', instruction_text: '把不符合美国审美的主图做个任务给美工做优化', sort_order: ++sortOrder, is_data_column: false },
            { name: '卖点广告视频方案', instruction_text: '专门针对2个以上的重点卖点做不同的广告视频方案给美工做视频并将视频应用去开广告', sort_order: ++sortOrder, is_data_column: false },
            { name: '国外风格图片方案', instruction_text: '参考国外卖家相似产品的图片风格A+风格做一套更符合国外审美的图片方案', sort_order: ++sortOrder, is_data_column: false },
            { name: '美化主图', instruction_text: '美化主图，找更好的主图方案', sort_order: ++sortOrder, is_data_column: false },
            { name: '主图加季节元素', instruction_text: '主图能加上夏季元素的尽量加上去（新品，出单极少产品可考虑在主图上加上圣诞元素）', sort_order: ++sortOrder, is_data_column: false },
            { name: '灵魂拷问广告视频开头', instruction_text: '做一个灵魂拷问的广告视频开头(痛点打法、焦虑打法的延伸)：15s/30s脚本模板', sort_order: ++sortOrder, is_data_column: false },
            { name: '主图/视频安全焦虑打法', instruction_text: '主图/视频安全焦虑打法：开场MOUTH-SAFE CHECK + 跌落耐摔镜头 + 宝宝玩耍 + CTA', sort_order: ++sortOrder, is_data_column: false },
            { name: '红人视频', instruction_text: '安排红人拍摄产品使用视频', sort_order: ++sortOrder, is_data_column: false },
            { name: 'GPT图片优化', instruction_text: '结合GPT进行图片优化：主图和附图A+', sort_order: ++sortOrder, is_data_column: false },
            { name: '附图更新到最新版', instruction_text: '附图更新到最新版', sort_order: ++sortOrder, is_data_column: false },
            { name: 'A+更新到最新版', instruction_text: 'A+更新到最新版', sort_order: ++sortOrder, is_data_column: false },
            { name: '主附图AB测试', instruction_text: '主附图做AB测试', sort_order: ++sortOrder, is_data_column: false },
            { name: '品牌感染力视频', instruction_text: '为此产品做一个精美且更多生活使用场景且更有品牌感染力的视频', sort_order: ++sortOrder, is_data_column: false },
            { name: '5种视频类型', instruction_text: '安排美工做够5种视频：产品细节展示视频，场景视频（红人视频），无人自动的逐帧动画视频，图文介绍视频', sort_order: ++sortOrder, is_data_column: false },
            { name: '持续添加够5个视频', instruction_text: '持续把产品添加够5个视频', sort_order: ++sortOrder, is_data_column: false },
            { name: 'GPT重做主图场景图', instruction_text: '让GPT重新做一版主图和场景图，有重要卖点，场景图也要突出重要卖点', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
    {
        sort_order: 11,
        name: '其它',
        items: [
            { name: '更新日期', table_ref: 'product_sop_records.updated_at', sort_order: ++sortOrder, is_data_column: true },
            { name: '减少低效产品投入', instruction_text: '把不打算继续投放时间运营的产品减少广告投入--减bid减预算', sort_order: ++sortOrder, is_data_column: false },
        ]
    },
];

module.exports = { modules };
